package ports

import (
	"time"

	"github.com/EslamYasser-Dev/simple-file-share/domain/models"
)

// ShareRepository stores and retrieves public share links. Implementations must
// be safe for concurrent use.
type ShareRepository interface {
	// Create persists a new share, replacing any existing share with the same
	// token. The token is generated by the caller.
	Create(share *models.Share) error
	// FindByToken looks up a share, returning domainerrors.ErrShareNotFound when
	// no share matches.
	FindByToken(token string) (*models.Share, error)
	// ListByOwner returns the shares owned by a username, newest first.
	ListByOwner(owner string) ([]*models.Share, error)
	// ListAll returns every stored share, newest first.
	ListAll() ([]*models.Share, error)
	// Delete removes the share with the given token, returning
	// domainerrors.ErrShareNotFound when no share matches.
	Delete(token string) error
	// PurgeExpired atomically removes shares whose validity window has passed
	// and returns the number removed.
	PurgeExpired(now time.Time) (int, error)
	// ConsumeDownload atomically records one download against a limited
	// link's budget. It returns domainerrors.ErrShareLimitReached when the
	// budget is already used up, so concurrent requests cannot overshoot.
	// Unlimited links are not tracked here and should not call it.
	ConsumeDownload(token string) error
}
