// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: fileshare/v1/fileshare.proto

package filesharev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	IsAdmin       bool                   `protobuf:"varint,2,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Enabled       bool                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	QuotaBytes    int64                  `protobuf:"varint,5,opt,name=quota_bytes,json=quotaBytes,proto3" json:"quota_bytes,omitempty"`
	Size          int64                  `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
	Files         int64                  `protobuf:"varint,7,opt,name=files,proto3" json:"files,omitempty"`
	Permissions   []string               `protobuf:"bytes,8,rep,name=permissions,proto3" json:"permissions,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_fileshare_v1_fileshare_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

func (x *User) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *User) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *User) GetQuotaBytes() int64 {
	if x != nil {
		return x.QuotaBytes
	}
	return 0
}

func (x *User) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *User) GetFiles() int64 {
	if x != nil {
		return x.Files
	}
	return 0
}

func (x *User) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *User) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type AuthInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SignupEnabled bool                   `protobuf:"varint,1,opt,name=signup_enabled,json=signupEnabled,proto3" json:"signup_enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthInfoResponse) Reset() {
	*x = AuthInfoResponse{}
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthInfoResponse) ProtoMessage() {}

func (x *AuthInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthInfoResponse.ProtoReflect.Descriptor instead.
func (*AuthInfoResponse) Descriptor() ([]byte, []int) {
	return file_fileshare_v1_fileshare_proto_rawDescGZIP(), []int{1}
}

func (x *AuthInfoResponse) GetSignupEnabled() bool {
	if x != nil {
		return x.SignupEnabled
	}
	return false
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_fileshare_v1_fileshare_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthenticateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateRequest) Reset() {
	*x = AuthenticateRequest{}
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateRequest) ProtoMessage() {}

func (x *AuthenticateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateRequest.ProtoReflect.Descriptor instead.
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return file_fileshare_v1_fileshare_proto_rawDescGZIP(), []int{3}
}

func (x *AuthenticateRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthenticateRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type MeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeRequest) Reset() {
	*x = MeRequest{}
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeRequest) ProtoMessage() {}

func (x *MeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeRequest.ProtoReflect.Descriptor instead.
func (*MeRequest) Descriptor() ([]byte, []int) {
	return file_fileshare_v1_fileshare_proto_rawDescGZIP(), []int{4}
}

type GetAuthInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthInfoRequest) Reset() {
	*x = GetAuthInfoRequest{}
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthInfoRequest) ProtoMessage() {}

func (x *GetAuthInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthInfoRequest.ProtoReflect.Descriptor instead.
func (*GetAuthInfoRequest) Descriptor() ([]byte, []int) {
	return file_fileshare_v1_fileshare_proto_rawDescGZIP(), []int{5}
}

type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_fileshare_v1_fileshare_proto_rawDescGZIP(), []int{6}
}

type UserStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	FileCount     int64                  `protobuf:"varint,2,opt,name=file_count,json=fileCount,proto3" json:"file_count,omitempty"`
	TotalSize     int64                  `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	IsAdmin       bool                   `protobuf:"varint,4,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	Enabled       bool                   `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`
	QuotaBytes    int64                  `protobuf:"varint,7,opt,name=quota_bytes,json=quotaBytes,proto3" json:"quota_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserStats) Reset() {
	*x = UserStats{}
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStats) ProtoMessage() {}

func (x *UserStats) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStats.ProtoReflect.Descriptor instead.
func (*UserStats) Descriptor() ([]byte, []int) {
	return file_fileshare_v1_fileshare_proto_rawDescGZIP(), []int{7}
}

func (x *UserStats) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserStats) GetFileCount() int64 {
	if x != nil {
		return x.FileCount
	}
	return 0
}

func (x *UserStats) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *UserStats) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

func (x *UserStats) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UserStats) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *UserStats) GetQuotaBytes() int64 {
	if x != nil {
		return x.QuotaBytes
	}
	return 0
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserStats           `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_fileshare_v1_fileshare_proto_rawDescGZIP(), []int{8}
}

func (x *ListUsersResponse) GetUsers() []*UserStats {
	if x != nil {
		return x.Users
	}
	return nil
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_fileshare_v1_fileshare_proto_rawDescGZIP(), []int{9}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	TokenType     string                 `protobuf:"bytes,2,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	ExpiresIn     int64                  `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_fileshare_v1_fileshare_proto_rawDescGZIP(), []int{10}
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResponse) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *LoginResponse) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_fileshare_v1_fileshare_proto_rawDescGZIP(), []int{11}
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_fileshare_v1_fileshare_proto_rawDescGZIP(), []int{12}
}

func (x *LogoutResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateShareRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Path             string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	ExpiresInSeconds int64                  `protobuf:"varint,2,opt,name=expires_in_seconds,json=expiresInSeconds,proto3" json:"expires_in_seconds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateShareRequest) Reset() {
	*x = CreateShareRequest{}
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShareRequest) ProtoMessage() {}

func (x *CreateShareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShareRequest.ProtoReflect.Descriptor instead.
func (*CreateShareRequest) Descriptor() ([]byte, []int) {
	return file_fileshare_v1_fileshare_proto_rawDescGZIP(), []int{13}
}

func (x *CreateShareRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CreateShareRequest) GetExpiresInSeconds() int64 {
	if x != nil {
		return x.ExpiresInSeconds
	}
	return 0
}

type Share struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Owner         string                 `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Share) Reset() {
	*x = Share{}
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Share) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Share) ProtoMessage() {}

func (x *Share) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Share.ProtoReflect.Descriptor instead.
func (*Share) Descriptor() ([]byte, []int) {
	return file_fileshare_v1_fileshare_proto_rawDescGZIP(), []int{14}
}

func (x *Share) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Share) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Share) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Share) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Share) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Share) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

type ListSharesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSharesRequest) Reset() {
	*x = ListSharesRequest{}
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSharesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSharesRequest) ProtoMessage() {}

func (x *ListSharesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSharesRequest.ProtoReflect.Descriptor instead.
func (*ListSharesRequest) Descriptor() ([]byte, []int) {
	return file_fileshare_v1_fileshare_proto_rawDescGZIP(), []int{15}
}

type ListSharesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shares        []*Share               `protobuf:"bytes,1,rep,name=shares,proto3" json:"shares,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSharesResponse) Reset() {
	*x = ListSharesResponse{}
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSharesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSharesResponse) ProtoMessage() {}

func (x *ListSharesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSharesResponse.ProtoReflect.Descriptor instead.
func (*ListSharesResponse) Descriptor() ([]byte, []int) {
	return file_fileshare_v1_fileshare_proto_rawDescGZIP(), []int{16}
}

func (x *ListSharesResponse) GetShares() []*Share {
	if x != nil {
		return x.Shares
	}
	return nil
}

type RevokeShareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeShareRequest) Reset() {
	*x = RevokeShareRequest{}
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeShareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeShareRequest) ProtoMessage() {}

func (x *RevokeShareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeShareRequest.ProtoReflect.Descriptor instead.
func (*RevokeShareRequest) Descriptor() ([]byte, []int) {
	return file_fileshare_v1_fileshare_proto_rawDescGZIP(), []int{17}
}

func (x *RevokeShareRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type RevokeShareResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeShareResponse) Reset() {
	*x = RevokeShareResponse{}
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeShareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeShareResponse) ProtoMessage() {}

func (x *RevokeShareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeShareResponse.ProtoReflect.Descriptor instead.
func (*RevokeShareResponse) Descriptor() ([]byte, []int) {
	return file_fileshare_v1_fileshare_proto_rawDescGZIP(), []int{18}
}

func (x *RevokeShareResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_fileshare_v1_fileshare_proto_rawDescGZIP(), []int{19}
}

type EventMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	User          string                 `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	At            string                 `protobuf:"bytes,4,opt,name=at,proto3" json:"at,omitempty"`
	Bytes         int64                  `protobuf:"varint,5,opt,name=bytes,proto3" json:"bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventMessage) Reset() {
	*x = EventMessage{}
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMessage) ProtoMessage() {}

func (x *EventMessage) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventMessage.ProtoReflect.Descriptor instead.
func (*EventMessage) Descriptor() ([]byte, []int) {
	return file_fileshare_v1_fileshare_proto_rawDescGZIP(), []int{20}
}

func (x *EventMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EventMessage) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *EventMessage) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *EventMessage) GetAt() string {
	if x != nil {
		return x.At
	}
	return ""
}

func (x *EventMessage) GetBytes() int64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	IsDir         bool                   `protobuf:"varint,4,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	Modified      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=modified,proto3" json:"modified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_fileshare_v1_fileshare_proto_rawDescGZIP(), []int{21}
}

func (x *FileInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileInfo) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *FileInfo) GetModified() *timestamppb.Timestamp {
	if x != nil {
		return x.Modified
	}
	return nil
}

type ListFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesRequest) Reset() {
	*x = ListFilesRequest{}
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesRequest) ProtoMessage() {}

func (x *ListFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesRequest.ProtoReflect.Descriptor instead.
func (*ListFilesRequest) Descriptor() ([]byte, []int) {
	return file_fileshare_v1_fileshare_proto_rawDescGZIP(), []int{22}
}

func (x *ListFilesRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ListFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*FileInfo            `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesResponse) Reset() {
	*x = ListFilesResponse{}
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesResponse) ProtoMessage() {}

func (x *ListFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesResponse.ProtoReflect.Descriptor instead.
func (*ListFilesResponse) Descriptor() ([]byte, []int) {
	return file_fileshare_v1_fileshare_proto_rawDescGZIP(), []int{23}
}

func (x *ListFilesResponse) GetFiles() []*FileInfo {
	if x != nil {
		return x.Files
	}
	return nil
}

type GetFileInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileInfoRequest) Reset() {
	*x = GetFileInfoRequest{}
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileInfoRequest) ProtoMessage() {}

func (x *GetFileInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileInfoRequest.ProtoReflect.Descriptor instead.
func (*GetFileInfoRequest) Descriptor() ([]byte, []int) {
	return file_fileshare_v1_fileshare_proto_rawDescGZIP(), []int{24}
}

func (x *GetFileInfoRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type SearchFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchFilesRequest) Reset() {
	*x = SearchFilesRequest{}
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchFilesRequest) ProtoMessage() {}

func (x *SearchFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchFilesRequest.ProtoReflect.Descriptor instead.
func (*SearchFilesRequest) Descriptor() ([]byte, []int) {
	return file_fileshare_v1_fileshare_proto_rawDescGZIP(), []int{25}
}

func (x *SearchFilesRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchFilesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*FileInfo            `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchFilesResponse) Reset() {
	*x = SearchFilesResponse{}
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchFilesResponse) ProtoMessage() {}

func (x *SearchFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchFilesResponse.ProtoReflect.Descriptor instead.
func (*SearchFilesResponse) Descriptor() ([]byte, []int) {
	return file_fileshare_v1_fileshare_proto_rawDescGZIP(), []int{26}
}

func (x *SearchFilesResponse) GetFiles() []*FileInfo {
	if x != nil {
		return x.Files
	}
	return nil
}

type CreateDirectoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDirectoryRequest) Reset() {
	*x = CreateDirectoryRequest{}
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDirectoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDirectoryRequest) ProtoMessage() {}

func (x *CreateDirectoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDirectoryRequest.ProtoReflect.Descriptor instead.
func (*CreateDirectoryRequest) Descriptor() ([]byte, []int) {
	return file_fileshare_v1_fileshare_proto_rawDescGZIP(), []int{27}
}

func (x *CreateDirectoryRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type CreateDirectoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDirectoryResponse) Reset() {
	*x = CreateDirectoryResponse{}
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDirectoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDirectoryResponse) ProtoMessage() {}

func (x *CreateDirectoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDirectoryResponse.ProtoReflect.Descriptor instead.
func (*CreateDirectoryResponse) Descriptor() ([]byte, []int) {
	return file_fileshare_v1_fileshare_proto_rawDescGZIP(), []int{28}
}

func (x *CreateDirectoryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeletePathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePathRequest) Reset() {
	*x = DeletePathRequest{}
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePathRequest) ProtoMessage() {}

func (x *DeletePathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePathRequest.ProtoReflect.Descriptor instead.
func (*DeletePathRequest) Descriptor() ([]byte, []int) {
	return file_fileshare_v1_fileshare_proto_rawDescGZIP(), []int{29}
}

func (x *DeletePathRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type DeletePathResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePathResponse) Reset() {
	*x = DeletePathResponse{}
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePathResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePathResponse) ProtoMessage() {}

func (x *DeletePathResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePathResponse.ProtoReflect.Descriptor instead.
func (*DeletePathResponse) Descriptor() ([]byte, []int) {
	return file_fileshare_v1_fileshare_proto_rawDescGZIP(), []int{30}
}

func (x *DeletePathResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateFileContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFileContentRequest) Reset() {
	*x = UpdateFileContentRequest{}
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFileContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFileContentRequest) ProtoMessage() {}

func (x *UpdateFileContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFileContentRequest.ProtoReflect.Descriptor instead.
func (*UpdateFileContentRequest) Descriptor() ([]byte, []int) {
	return file_fileshare_v1_fileshare_proto_rawDescGZIP(), []int{31}
}

func (x *UpdateFileContentRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *UpdateFileContentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type UpdateFileContentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFileContentResponse) Reset() {
	*x = UpdateFileContentResponse{}
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFileContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFileContentResponse) ProtoMessage() {}

func (x *UpdateFileContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFileContentResponse.ProtoReflect.Descriptor instead.
func (*UpdateFileContentResponse) Descriptor() ([]byte, []int) {
	return file_fileshare_v1_fileshare_proto_rawDescGZIP(), []int{32}
}

func (x *UpdateFileContentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateFileContentResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type UploadMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Destination directory (virtual, namespace-scoped).
	Path          string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Filename      string `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadMetadata) Reset() {
	*x = UploadMetadata{}
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMetadata) ProtoMessage() {}

func (x *UploadMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMetadata.ProtoReflect.Descriptor instead.
func (*UploadMetadata) Descriptor() ([]byte, []int) {
	return file_fileshare_v1_fileshare_proto_rawDescGZIP(), []int{33}
}

func (x *UploadMetadata) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *UploadMetadata) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type UploadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*UploadRequest_Metadata
	//	*UploadRequest_Chunk
	Payload       isUploadRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadRequest) Reset() {
	*x = UploadRequest{}
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRequest) ProtoMessage() {}

func (x *UploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRequest.ProtoReflect.Descriptor instead.
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return file_fileshare_v1_fileshare_proto_rawDescGZIP(), []int{34}
}

func (x *UploadRequest) GetPayload() isUploadRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *UploadRequest) GetMetadata() *UploadMetadata {
	if x != nil {
		if x, ok := x.Payload.(*UploadRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *UploadRequest) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Payload.(*UploadRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isUploadRequest_Payload interface {
	isUploadRequest_Payload()
}

type UploadRequest_Metadata struct {
	Metadata *UploadMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type UploadRequest_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*UploadRequest_Metadata) isUploadRequest_Payload() {}

func (*UploadRequest_Chunk) isUploadRequest_Payload() {}

type UploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResponse) Reset() {
	*x = UploadResponse{}
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResponse) ProtoMessage() {}

func (x *UploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResponse.ProtoReflect.Descriptor instead.
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return file_fileshare_v1_fileshare_proto_rawDescGZIP(), []int{35}
}

func (x *UploadResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *UploadResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type DownloadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadFileRequest) Reset() {
	*x = DownloadFileRequest{}
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileRequest) ProtoMessage() {}

func (x *DownloadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFileRequest.ProtoReflect.Descriptor instead.
func (*DownloadFileRequest) Descriptor() ([]byte, []int) {
	return file_fileshare_v1_fileshare_proto_rawDescGZIP(), []int{36}
}

func (x *DownloadFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type DownloadChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Set on the first chunk only.
	Filename      string `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Data          []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadChunk) Reset() {
	*x = DownloadChunk{}
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadChunk) ProtoMessage() {}

func (x *DownloadChunk) ProtoReflect() protoreflect.Message {
	mi := &file_fileshare_v1_fileshare_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadChunk.ProtoReflect.Descriptor instead.
func (*DownloadChunk) Descriptor() ([]byte, []int) {
	return file_fileshare_v1_fileshare_proto_rawDescGZIP(), []int{37}
}

func (x *DownloadChunk) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *DownloadChunk) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *DownloadChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_fileshare_v1_fileshare_proto protoreflect.FileDescriptor

const file_fileshare_v1_fileshare_proto_rawDesc = "" +
	"\n" +
	"\x1cfileshare/v1/fileshare.proto\x12\ffileshare.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf7\x01\n" +
	"\x04User\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x19\n" +
	"\bis_admin\x18\x02 \x01(\bR\aisAdmin\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x12\x1f\n" +
	"\vquota_bytes\x18\x05 \x01(\x03R\n" +
	"quotaBytes\x12\x12\n" +
	"\x04size\x18\x06 \x01(\x03R\x04size\x12\x14\n" +
	"\x05files\x18\a \x01(\x03R\x05files\x12 \n" +
	"\vpermissions\x18\b \x03(\tR\vpermissions\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\"9\n" +
	"\x10AuthInfoResponse\x12%\n" +
	"\x0esignup_enabled\x18\x01 \x01(\bR\rsignupEnabled\"I\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"M\n" +
	"\x13AuthenticateRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\v\n" +
	"\tMeRequest\"\x14\n" +
	"\x12GetAuthInfoRequest\"\x12\n" +
	"\x10ListUsersRequest\"\xcf\x01\n" +
	"\tUserStats\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"file_count\x18\x02 \x01(\x03R\tfileCount\x12\x1d\n" +
	"\n" +
	"total_size\x18\x03 \x01(\x03R\ttotalSize\x12\x19\n" +
	"\bis_admin\x18\x04 \x01(\bR\aisAdmin\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\x12\x18\n" +
	"\aenabled\x18\x06 \x01(\bR\aenabled\x12\x1f\n" +
	"\vquota_bytes\x18\a \x01(\x03R\n" +
	"quotaBytes\"B\n" +
	"\x11ListUsersResponse\x12-\n" +
	"\x05users\x18\x01 \x03(\v2\x17.fileshare.v1.UserStatsR\x05users\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"p\n" +
	"\rLoginResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x1d\n" +
	"\n" +
	"token_type\x18\x02 \x01(\tR\ttokenType\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x03R\texpiresIn\"\x0f\n" +
	"\rLogoutRequest\"(\n" +
	"\x0eLogoutResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"V\n" +
	"\x12CreateShareRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12,\n" +
	"\x12expires_in_seconds\x18\x02 \x01(\x03R\x10expiresInSeconds\"\x99\x01\n" +
	"\x05Share\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05owner\x18\x04 \x01(\tR\x05owner\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\tR\texpiresAt\"\x13\n" +
	"\x11ListSharesRequest\"A\n" +
	"\x12ListSharesResponse\x12+\n" +
	"\x06shares\x18\x01 \x03(\v2\x13.fileshare.v1.ShareR\x06shares\"*\n" +
	"\x12RevokeShareRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"/\n" +
	"\x13RevokeShareResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x12\n" +
	"\x10SubscribeRequest\"p\n" +
	"\fEventMessage\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04user\x18\x03 \x01(\tR\x04user\x12\x0e\n" +
	"\x02at\x18\x04 \x01(\tR\x02at\x12\x14\n" +
	"\x05bytes\x18\x05 \x01(\x03R\x05bytes\"\x95\x01\n" +
	"\bFileInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x15\n" +
	"\x06is_dir\x18\x04 \x01(\bR\x05isDir\x126\n" +
	"\bmodified\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bmodified\"&\n" +
	"\x10ListFilesRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"A\n" +
	"\x11ListFilesResponse\x12,\n" +
	"\x05files\x18\x01 \x03(\v2\x16.fileshare.v1.FileInfoR\x05files\"(\n" +
	"\x12GetFileInfoRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"@\n" +
	"\x12SearchFilesRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"C\n" +
	"\x13SearchFilesResponse\x12,\n" +
	"\x05files\x18\x01 \x03(\v2\x16.fileshare.v1.FileInfoR\x05files\",\n" +
	"\x16CreateDirectoryRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"3\n" +
	"\x17CreateDirectoryResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"'\n" +
	"\x11DeletePathRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\".\n" +
	"\x12DeletePathResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"H\n" +
	"\x18UpdateFileContentRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"I\n" +
	"\x19UpdateFileContentResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\"@\n" +
	"\x0eUploadMetadata\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\"n\n" +
	"\rUploadRequest\x12:\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1c.fileshare.v1.UploadMetadataH\x00R\bmetadata\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\t\n" +
	"\apayload\"8\n" +
	"\x0eUploadResponse\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\")\n" +
	"\x13DownloadFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"b\n" +
	"\rDownloadChunk\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data2\xec\x03\n" +
	"\vAuthService\x12=\n" +
	"\bRegister\x12\x1d.fileshare.v1.RegisterRequest\x1a\x12.fileshare.v1.User\x12E\n" +
	"\fAuthenticate\x12!.fileshare.v1.AuthenticateRequest\x1a\x12.fileshare.v1.User\x121\n" +
	"\x02Me\x12\x17.fileshare.v1.MeRequest\x1a\x12.fileshare.v1.User\x12O\n" +
	"\vGetAuthInfo\x12 .fileshare.v1.GetAuthInfoRequest\x1a\x1e.fileshare.v1.AuthInfoResponse\x12L\n" +
	"\tListUsers\x12\x1e.fileshare.v1.ListUsersRequest\x1a\x1f.fileshare.v1.ListUsersResponse\x12@\n" +
	"\x05Login\x12\x1a.fileshare.v1.LoginRequest\x1a\x1b.fileshare.v1.LoginResponse\x12C\n" +
	"\x06Logout\x12\x1b.fileshare.v1.LogoutRequest\x1a\x1c.fileshare.v1.LogoutResponse2\xf9\x01\n" +
	"\fShareService\x12D\n" +
	"\vCreateShare\x12 .fileshare.v1.CreateShareRequest\x1a\x13.fileshare.v1.Share\x12O\n" +
	"\n" +
	"ListShares\x12\x1f.fileshare.v1.ListSharesRequest\x1a .fileshare.v1.ListSharesResponse\x12R\n" +
	"\vRevokeShare\x12 .fileshare.v1.RevokeShareRequest\x1a!.fileshare.v1.RevokeShareResponse2Z\n" +
	"\rEventsService\x12I\n" +
	"\tSubscribe\x12\x1e.fileshare.v1.SubscribeRequest\x1a\x1a.fileshare.v1.EventMessage0\x012\xac\x05\n" +
	"\vFileService\x12L\n" +
	"\tListFiles\x12\x1e.fileshare.v1.ListFilesRequest\x1a\x1f.fileshare.v1.ListFilesResponse\x12G\n" +
	"\vGetFileInfo\x12 .fileshare.v1.GetFileInfoRequest\x1a\x16.fileshare.v1.FileInfo\x12R\n" +
	"\vSearchFiles\x12 .fileshare.v1.SearchFilesRequest\x1a!.fileshare.v1.SearchFilesResponse\x12^\n" +
	"\x0fCreateDirectory\x12$.fileshare.v1.CreateDirectoryRequest\x1a%.fileshare.v1.CreateDirectoryResponse\x12O\n" +
	"\n" +
	"DeletePath\x12\x1f.fileshare.v1.DeletePathRequest\x1a .fileshare.v1.DeletePathResponse\x12d\n" +
	"\x11UpdateFileContent\x12&.fileshare.v1.UpdateFileContentRequest\x1a'.fileshare.v1.UpdateFileContentResponse\x12I\n" +
	"\n" +
	"UploadFile\x12\x1b.fileshare.v1.UploadRequest\x1a\x1c.fileshare.v1.UploadResponse(\x01\x12P\n" +
	"\fDownloadFile\x12!.fileshare.v1.DownloadFileRequest\x1a\x1b.fileshare.v1.DownloadChunk0\x01BQZOgithub.com/EslamYasser-Dev/simple-file-share/api/proto/fileshare/v1;filesharev1b\x06proto3"

var (
	file_fileshare_v1_fileshare_proto_rawDescOnce sync.Once
	file_fileshare_v1_fileshare_proto_rawDescData []byte
)

func file_fileshare_v1_fileshare_proto_rawDescGZIP() []byte {
	file_fileshare_v1_fileshare_proto_rawDescOnce.Do(func() {
		file_fileshare_v1_fileshare_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fileshare_v1_fileshare_proto_rawDesc), len(file_fileshare_v1_fileshare_proto_rawDesc)))
	})
	return file_fileshare_v1_fileshare_proto_rawDescData
}

var file_fileshare_v1_fileshare_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_fileshare_v1_fileshare_proto_goTypes = []any{
	(*User)(nil),                      // 0: fileshare.v1.User
	(*AuthInfoResponse)(nil),          // 1: fileshare.v1.AuthInfoResponse
	(*RegisterRequest)(nil),           // 2: fileshare.v1.RegisterRequest
	(*AuthenticateRequest)(nil),       // 3: fileshare.v1.AuthenticateRequest
	(*MeRequest)(nil),                 // 4: fileshare.v1.MeRequest
	(*GetAuthInfoRequest)(nil),        // 5: fileshare.v1.GetAuthInfoRequest
	(*ListUsersRequest)(nil),          // 6: fileshare.v1.ListUsersRequest
	(*UserStats)(nil),                 // 7: fileshare.v1.UserStats
	(*ListUsersResponse)(nil),         // 8: fileshare.v1.ListUsersResponse
	(*LoginRequest)(nil),              // 9: fileshare.v1.LoginRequest
	(*LoginResponse)(nil),             // 10: fileshare.v1.LoginResponse
	(*LogoutRequest)(nil),             // 11: fileshare.v1.LogoutRequest
	(*LogoutResponse)(nil),            // 12: fileshare.v1.LogoutResponse
	(*CreateShareRequest)(nil),        // 13: fileshare.v1.CreateShareRequest
	(*Share)(nil),                     // 14: fileshare.v1.Share
	(*ListSharesRequest)(nil),         // 15: fileshare.v1.ListSharesRequest
	(*ListSharesResponse)(nil),        // 16: fileshare.v1.ListSharesResponse
	(*RevokeShareRequest)(nil),        // 17: fileshare.v1.RevokeShareRequest
	(*RevokeShareResponse)(nil),       // 18: fileshare.v1.RevokeShareResponse
	(*SubscribeRequest)(nil),          // 19: fileshare.v1.SubscribeRequest
	(*EventMessage)(nil),              // 20: fileshare.v1.EventMessage
	(*FileInfo)(nil),                  // 21: fileshare.v1.FileInfo
	(*ListFilesRequest)(nil),          // 22: fileshare.v1.ListFilesRequest
	(*ListFilesResponse)(nil),         // 23: fileshare.v1.ListFilesResponse
	(*GetFileInfoRequest)(nil),        // 24: fileshare.v1.GetFileInfoRequest
	(*SearchFilesRequest)(nil),        // 25: fileshare.v1.SearchFilesRequest
	(*SearchFilesResponse)(nil),       // 26: fileshare.v1.SearchFilesResponse
	(*CreateDirectoryRequest)(nil),    // 27: fileshare.v1.CreateDirectoryRequest
	(*CreateDirectoryResponse)(nil),   // 28: fileshare.v1.CreateDirectoryResponse
	(*DeletePathRequest)(nil),         // 29: fileshare.v1.DeletePathRequest
	(*DeletePathResponse)(nil),        // 30: fileshare.v1.DeletePathResponse
	(*UpdateFileContentRequest)(nil),  // 31: fileshare.v1.UpdateFileContentRequest
	(*UpdateFileContentResponse)(nil), // 32: fileshare.v1.UpdateFileContentResponse
	(*UploadMetadata)(nil),            // 33: fileshare.v1.UploadMetadata
	(*UploadRequest)(nil),             // 34: fileshare.v1.UploadRequest
	(*UploadResponse)(nil),            // 35: fileshare.v1.UploadResponse
	(*DownloadFileRequest)(nil),       // 36: fileshare.v1.DownloadFileRequest
	(*DownloadChunk)(nil),             // 37: fileshare.v1.DownloadChunk
	(*timestamppb.Timestamp)(nil),     // 38: google.protobuf.Timestamp
}
var file_fileshare_v1_fileshare_proto_depIdxs = []int32{
	7,  // 0: fileshare.v1.ListUsersResponse.users:type_name -> fileshare.v1.UserStats
	14, // 1: fileshare.v1.ListSharesResponse.shares:type_name -> fileshare.v1.Share
	38, // 2: fileshare.v1.FileInfo.modified:type_name -> google.protobuf.Timestamp
	21, // 3: fileshare.v1.ListFilesResponse.files:type_name -> fileshare.v1.FileInfo
	21, // 4: fileshare.v1.SearchFilesResponse.files:type_name -> fileshare.v1.FileInfo
	33, // 5: fileshare.v1.UploadRequest.metadata:type_name -> fileshare.v1.UploadMetadata
	2,  // 6: fileshare.v1.AuthService.Register:input_type -> fileshare.v1.RegisterRequest
	3,  // 7: fileshare.v1.AuthService.Authenticate:input_type -> fileshare.v1.AuthenticateRequest
	4,  // 8: fileshare.v1.AuthService.Me:input_type -> fileshare.v1.MeRequest
	5,  // 9: fileshare.v1.AuthService.GetAuthInfo:input_type -> fileshare.v1.GetAuthInfoRequest
	6,  // 10: fileshare.v1.AuthService.ListUsers:input_type -> fileshare.v1.ListUsersRequest
	9,  // 11: fileshare.v1.AuthService.Login:input_type -> fileshare.v1.LoginRequest
	11, // 12: fileshare.v1.AuthService.Logout:input_type -> fileshare.v1.LogoutRequest
	13, // 13: fileshare.v1.ShareService.CreateShare:input_type -> fileshare.v1.CreateShareRequest
	15, // 14: fileshare.v1.ShareService.ListShares:input_type -> fileshare.v1.ListSharesRequest
	17, // 15: fileshare.v1.ShareService.RevokeShare:input_type -> fileshare.v1.RevokeShareRequest
	19, // 16: fileshare.v1.EventsService.Subscribe:input_type -> fileshare.v1.SubscribeRequest
	22, // 17: fileshare.v1.FileService.ListFiles:input_type -> fileshare.v1.ListFilesRequest
	24, // 18: fileshare.v1.FileService.GetFileInfo:input_type -> fileshare.v1.GetFileInfoRequest
	25, // 19: fileshare.v1.FileService.SearchFiles:input_type -> fileshare.v1.SearchFilesRequest
	27, // 20: fileshare.v1.FileService.CreateDirectory:input_type -> fileshare.v1.CreateDirectoryRequest
	29, // 21: fileshare.v1.FileService.DeletePath:input_type -> fileshare.v1.DeletePathRequest
	31, // 22: fileshare.v1.FileService.UpdateFileContent:input_type -> fileshare.v1.UpdateFileContentRequest
	34, // 23: fileshare.v1.FileService.UploadFile:input_type -> fileshare.v1.UploadRequest
	36, // 24: fileshare.v1.FileService.DownloadFile:input_type -> fileshare.v1.DownloadFileRequest
	0,  // 25: fileshare.v1.AuthService.Register:output_type -> fileshare.v1.User
	0,  // 26: fileshare.v1.AuthService.Authenticate:output_type -> fileshare.v1.User
	0,  // 27: fileshare.v1.AuthService.Me:output_type -> fileshare.v1.User
	1,  // 28: fileshare.v1.AuthService.GetAuthInfo:output_type -> fileshare.v1.AuthInfoResponse
	8,  // 29: fileshare.v1.AuthService.ListUsers:output_type -> fileshare.v1.ListUsersResponse
	10, // 30: fileshare.v1.AuthService.Login:output_type -> fileshare.v1.LoginResponse
	12, // 31: fileshare.v1.AuthService.Logout:output_type -> fileshare.v1.LogoutResponse
	14, // 32: fileshare.v1.ShareService.CreateShare:output_type -> fileshare.v1.Share
	16, // 33: fileshare.v1.ShareService.ListShares:output_type -> fileshare.v1.ListSharesResponse
	18, // 34: fileshare.v1.ShareService.RevokeShare:output_type -> fileshare.v1.RevokeShareResponse
	20, // 35: fileshare.v1.EventsService.Subscribe:output_type -> fileshare.v1.EventMessage
	23, // 36: fileshare.v1.FileService.ListFiles:output_type -> fileshare.v1.ListFilesResponse
	21, // 37: fileshare.v1.FileService.GetFileInfo:output_type -> fileshare.v1.FileInfo
	26, // 38: fileshare.v1.FileService.SearchFiles:output_type -> fileshare.v1.SearchFilesResponse
	28, // 39: fileshare.v1.FileService.CreateDirectory:output_type -> fileshare.v1.CreateDirectoryResponse
	30, // 40: fileshare.v1.FileService.DeletePath:output_type -> fileshare.v1.DeletePathResponse
	32, // 41: fileshare.v1.FileService.UpdateFileContent:output_type -> fileshare.v1.UpdateFileContentResponse
	35, // 42: fileshare.v1.FileService.UploadFile:output_type -> fileshare.v1.UploadResponse
	37, // 43: fileshare.v1.FileService.DownloadFile:output_type -> fileshare.v1.DownloadChunk
	25, // [25:44] is the sub-list for method output_type
	6,  // [6:25] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_fileshare_v1_fileshare_proto_init() }
func file_fileshare_v1_fileshare_proto_init() {
	if File_fileshare_v1_fileshare_proto != nil {
		return
	}
	file_fileshare_v1_fileshare_proto_msgTypes[34].OneofWrappers = []any{
		(*UploadRequest_Metadata)(nil),
		(*UploadRequest_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fileshare_v1_fileshare_proto_rawDesc), len(file_fileshare_v1_fileshare_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_fileshare_v1_fileshare_proto_goTypes,
		DependencyIndexes: file_fileshare_v1_fileshare_proto_depIdxs,
		MessageInfos:      file_fileshare_v1_fileshare_proto_msgTypes,
	}.Build()
	File_fileshare_v1_fileshare_proto = out.File
	file_fileshare_v1_fileshare_proto_goTypes = nil
	file_fileshare_v1_fileshare_proto_depIdxs = nil
}
